db:
  user: root
  password: password
  host: mysql
  port: 3306
  database: kcauth
  charset: utf8mb4

redis:
  addr: redis:6379
  password:
  db: 0

storage:
  provider: minio
  endpoint: "minio:9000"
  region: "zhuhai-1"
  accessKeyID: "T64JKDV276dJp10"
  secretAccessKey: "1JzdCtZqgiys22q"
  stsAccessKeyID: "user"
  stsSecretAccessKey: "LRfETL5HGUGAGv9"
  attatchBucket: "attatch"

storage_public_url:
  attatch: "http://localhost:9000/attatch"

auth:
  enabled_providers:
    - "account"
  jwt:
    issuer: "kcaitech.com"

auth_admin:
  enabled: true
  secret_key: "YOUR_ADMIN_SECRET_KEY"
  accounts:
    - username: "admin"
      password: "$2a$10$fG44fQ/dghOcCqLJUHWJterKptRWn4DNbnb1H9QK5ec9Lij2srSA2"
      roles:
        - "super_admin"
    - username: "operator"
      password: "YOUR_OPERATOR_PASSWORD_HASH"
      roles:
        - "user_manager"
  allowed_ips:
    - "127.0.0.1"
    - "::1"
  require_tls: false
  session_ttl: 30
  login_timeout: 60

auth_trusted_clients:
  - client_id: "kcserver"
    client_secret: "$2a$10$fG44fQ/dghOcCqLJUHWJterKptRWn4DNbnb1H9QK5ec9Lij2srSA2"
    allowed_ips:
      - "*"
    scopes:
      - "read:users" 